### ISSUE TITLE
cifilter.io down (no DNS record)

### ISSUE THREAD

**Issue by janbrasna** [noahsark769/cifilter.app#183]
@noahsark769 Hi, seems your .io domains don't resolve: https://downforeveryoneorjustme.com/cifilter.io

![Screen Shot 2024-01-18 at 15 25 57](https://github.com/noahsark769/cifilter.io/assets/1784648/40215967-7688-485a-a5cd-379807af62cc)

![Screen Shot 2024-01-18 at 15 24 50](https://github.com/noahsark769/cifilter.io/assets/1784648/f5f08a54-cb3d-4527-89da-41e625a702e0)

(same for cifilter.io and getfluency.io…)

**Comment by janbrasna** [comment]
(if anyone needs to browse the filter reference, i've deployed the gh-pages to a mirror https://cifilters-ref.netlify.app for now…)

**Comment by noahsark769** [comment]
Hey @janbrasna, thanks for reporting this! Due to some shennanigans with the domain registration, I moved the domain to https://cifilter.app. Should be up there now!

**Comment by janbrasna** [comment]
Sorry to hear. Yup the site is accessible now, I was about to PR the URL changes et al. to bring it up to date but noticed you've started updating the links already…

Probably this one needs updating too:
https://github.com/noahsark769/cifilter.app/blob/ad44f6efc19374454524ace4e6f9e4670b976424/web/gatsby-config.js#L3-L4
as the builds seem to be failing now:/ — so the changes are not deployed live FYI.

**Comment by janbrasna** [comment]
~(ah, actually there are errors from probably running the jobs with Node 13… maybe try bumping the `actions/setup-node` to `@v4` and using at least Node 16 to get rid of the errors…)~ or skip the build+commit CI action completely and add some deploy starter action as [gatsby.yml](https://github.com/actions/starter-workflows/blob/main/pages/gatsby.yml) to skip the `gh-pages` branch completely and build to `github-pages` deployment straight from the build artifacts…

EDIT: you know what, I've fixed up the manifest and untangled the dependencies etc. for you + created a new workflow for building the Gatsby docs straight to github-pages deployment, see #196
